version: '3.9'
services:
  db_product_feedback:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./docker-data/db-data:/var/lib/postgresql/data
volumes:
  data_db_product_feedback:
    driver: local
